/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Cylinder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cylinder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cylinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModelJNI.delete_Cylinder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Cylinder() {
    this(NoiseModelJNI.new_Cylinder__SWIG_0(), true);
  }

  public Cylinder(SWIGTYPE_p_noise__module__Module module) {
    this(NoiseModelJNI.new_Cylinder__SWIG_1(SWIGTYPE_p_noise__module__Module.getCPtr(module)), true);
  }

  public SWIGTYPE_p_noise__module__Module GetModule() {
    return new SWIGTYPE_p_noise__module__Module(NoiseModelJNI.Cylinder_GetModule(swigCPtr, this), false);
  }

  public double GetValue(double angle, double height) {
    return NoiseModelJNI.Cylinder_GetValue(swigCPtr, this, angle, height);
  }

  public void SetModule(SWIGTYPE_p_noise__module__Module module) {
    NoiseModelJNI.Cylinder_SetModule(swigCPtr, this, SWIGTYPE_p_noise__module__Module.getCPtr(module));
  }

}
