/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Exponent extends Module {
  private transient long swigCPtr;

  protected Exponent(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Exponent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Exponent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Exponent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Exponent() {
    this(NoiseModuleJNI.new_Exponent(), true);
  }

  public double GetExponent() {
    return NoiseModuleJNI.Exponent_GetExponent(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Exponent_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Exponent_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetExponent(double exponent) {
    NoiseModuleJNI.Exponent_SetExponent(swigCPtr, this, exponent);
  }

}
