/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Line {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Line(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Line obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModelJNI.delete_Line(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Line() {
    this(NoiseModelJNI.new_Line__SWIG_0(), true);
  }

  public Line(SWIGTYPE_p_noise__module__Module module) {
    this(NoiseModelJNI.new_Line__SWIG_1(SWIGTYPE_p_noise__module__Module.getCPtr(module)), true);
  }

  public boolean GetAttenuate() {
    return NoiseModelJNI.Line_GetAttenuate(swigCPtr, this);
  }

  public SWIGTYPE_p_noise__module__Module GetModule() {
    return new SWIGTYPE_p_noise__module__Module(NoiseModelJNI.Line_GetModule(swigCPtr, this), false);
  }

  public double GetValue(double p) {
    return NoiseModelJNI.Line_GetValue(swigCPtr, this, p);
  }

  public void SetAttenuate(boolean att) {
    NoiseModelJNI.Line_SetAttenuate(swigCPtr, this, att);
  }

  public void SetEndPoint(double x, double y, double z) {
    NoiseModelJNI.Line_SetEndPoint(swigCPtr, this, x, y, z);
  }

  public void SetModule(SWIGTYPE_p_noise__module__Module module) {
    NoiseModelJNI.Line_SetModule(swigCPtr, this, SWIGTYPE_p_noise__module__Module.getCPtr(module));
  }

  public void SetStartPoint(double x, double y, double z) {
    NoiseModelJNI.Line_SetStartPoint(swigCPtr, this, x, y, z);
  }

}
