/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Plane {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Plane(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Plane obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModelJNI.delete_Plane(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Plane() {
    this(NoiseModelJNI.new_Plane__SWIG_0(), true);
  }

  public Plane(SWIGTYPE_p_noise__module__Module module) {
    this(NoiseModelJNI.new_Plane__SWIG_1(SWIGTYPE_p_noise__module__Module.getCPtr(module)), true);
  }

  public SWIGTYPE_p_noise__module__Module GetModule() {
    return new SWIGTYPE_p_noise__module__Module(NoiseModelJNI.Plane_GetModule(swigCPtr, this), false);
  }

  public double GetValue(double x, double z) {
    return NoiseModelJNI.Plane_GetValue(swigCPtr, this, x, z);
  }

  public void SetModule(SWIGTYPE_p_noise__module__Module module) {
    NoiseModelJNI.Plane_SetModule(swigCPtr, this, SWIGTYPE_p_noise__module__Module.getCPtr(module));
  }

}
