/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Select extends Module {
  private transient long swigCPtr;

  protected Select(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Select_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Select obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Select(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Select() {
    this(NoiseModuleJNI.new_Select(), true);
  }

  public Module GetControlModule() {
    return new Module(NoiseModuleJNI.Select_GetControlModule(swigCPtr, this), false);
  }

  public double GetEdgeFalloff() {
    return NoiseModuleJNI.Select_GetEdgeFalloff(swigCPtr, this);
  }

  public double GetLowerBound() {
    return NoiseModuleJNI.Select_GetLowerBound(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Select_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetUpperBound() {
    return NoiseModuleJNI.Select_GetUpperBound(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Select_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetBounds(double lowerBound, double upperBound) {
    NoiseModuleJNI.Select_SetBounds(swigCPtr, this, lowerBound, upperBound);
  }

  public void SetControlModule(Module controlModule) {
    NoiseModuleJNI.Select_SetControlModule(swigCPtr, this, Module.getCPtr(controlModule), controlModule);
  }

  public void SetEdgeFalloff(double edgeFalloff) {
    NoiseModuleJNI.Select_SetEdgeFalloff(swigCPtr, this, edgeFalloff);
  }

}
