/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class Color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Color() {
    this(NoiseUtilsJNI.new_Color__SWIG_0(), true);
  }

  public Color(short r, short g, short b, short a) {
    this(NoiseUtilsJNI.new_Color__SWIG_1(r, g, b, a), true);
  }

  public void setAlpha(short value) {
    NoiseUtilsJNI.Color_alpha_set(swigCPtr, this, value);
  }

  public short getAlpha() {
    return NoiseUtilsJNI.Color_alpha_get(swigCPtr, this);
  }

  public void setBlue(short value) {
    NoiseUtilsJNI.Color_blue_set(swigCPtr, this, value);
  }

  public short getBlue() {
    return NoiseUtilsJNI.Color_blue_get(swigCPtr, this);
  }

  public void setGreen(short value) {
    NoiseUtilsJNI.Color_green_set(swigCPtr, this, value);
  }

  public short getGreen() {
    return NoiseUtilsJNI.Color_green_get(swigCPtr, this);
  }

  public void setRed(short value) {
    NoiseUtilsJNI.Color_red_set(swigCPtr, this, value);
  }

  public short getRed() {
    return NoiseUtilsJNI.Color_red_get(swigCPtr, this);
  }

}
