/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class GradientPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public GradientPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GradientPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_GradientPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(double value) {
    NoiseUtilsJNI.GradientPoint_pos_set(swigCPtr, this, value);
  }

  public double getPos() {
    return NoiseUtilsJNI.GradientPoint_pos_get(swigCPtr, this);
  }

  public void setColor(Color value) {
    NoiseUtilsJNI.GradientPoint_color_set(swigCPtr, this, Color.getCPtr(value), value);
  }

  public Color getColor() {
    long cPtr = NoiseUtilsJNI.GradientPoint_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public GradientPoint() {
    this(NoiseUtilsJNI.new_GradientPoint(), true);
  }

}
