/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class Image {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Image() {
    this(NoiseUtilsJNI.new_Image__SWIG_0(), true);
  }

  public Image(int width, int height) {
    this(NoiseUtilsJNI.new_Image__SWIG_1(width, height), true);
  }

  public Image(Image rhs) {
    this(NoiseUtilsJNI.new_Image__SWIG_2(Image.getCPtr(rhs), rhs), true);
  }

  public void Clear(Color value) {
    NoiseUtilsJNI.Image_Clear(swigCPtr, this, Color.getCPtr(value), value);
  }

  public Color GetBorderValue() {
    return new Color(NoiseUtilsJNI.Image_GetBorderValue(swigCPtr, this), true);
  }

  public Color GetConstSlabPtr() {
    long cPtr = NoiseUtilsJNI.Image_GetConstSlabPtr__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public Color GetConstSlabPtr(int row) {
    long cPtr = NoiseUtilsJNI.Image_GetConstSlabPtr__SWIG_1(swigCPtr, this, row);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public Color GetConstSlabPtr(int x, int y) {
    long cPtr = NoiseUtilsJNI.Image_GetConstSlabPtr__SWIG_2(swigCPtr, this, x, y);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public int GetHeight() {
    return NoiseUtilsJNI.Image_GetHeight(swigCPtr, this);
  }

  public long GetMemUsed() {
    return NoiseUtilsJNI.Image_GetMemUsed(swigCPtr, this);
  }

  public Color GetSlabPtr() {
    long cPtr = NoiseUtilsJNI.Image_GetSlabPtr__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public Color GetSlabPtr(int row) {
    long cPtr = NoiseUtilsJNI.Image_GetSlabPtr__SWIG_1(swigCPtr, this, row);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public Color GetSlabPtr(int x, int y) {
    long cPtr = NoiseUtilsJNI.Image_GetSlabPtr__SWIG_2(swigCPtr, this, x, y);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public int GetStride() {
    return NoiseUtilsJNI.Image_GetStride(swigCPtr, this);
  }

  public Color GetValue(int x, int y) {
    return new Color(NoiseUtilsJNI.Image_GetValue(swigCPtr, this, x, y), true);
  }

  public int GetWidth() {
    return NoiseUtilsJNI.Image_GetWidth(swigCPtr, this);
  }

  public void ReclaimMem() {
    NoiseUtilsJNI.Image_ReclaimMem(swigCPtr, this);
  }

  public void SetBorderValue(Color borderValue) {
    NoiseUtilsJNI.Image_SetBorderValue(swigCPtr, this, Color.getCPtr(borderValue), borderValue);
  }

  public void SetSize(int width, int height) {
    NoiseUtilsJNI.Image_SetSize(swigCPtr, this, width, height);
  }

  public void SetValue(int x, int y, Color value) {
    NoiseUtilsJNI.Image_SetValue(swigCPtr, this, x, y, Color.getCPtr(value), value);
  }

  public void TakeOwnership(Image source) {
    NoiseUtilsJNI.Image_TakeOwnership(swigCPtr, this, Image.getCPtr(source), source);
  }

}
