/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

public class NoiseUtils {
  public static int getRASTER_MAX_WIDTH() {
    return NoiseUtilsJNI.RASTER_MAX_WIDTH_get();
  }

  public static int getRASTER_MAX_HEIGHT() {
    return NoiseUtilsJNI.RASTER_MAX_HEIGHT_get();
  }

  public static int getRASTER_STRIDE_BOUNDARY() {
    return NoiseUtilsJNI.RASTER_STRIDE_BOUNDARY_get();
  }

  public static double getDEFAULT_METERS_PER_POINT() {
    return NoiseUtilsJNI.DEFAULT_METERS_PER_POINT_get();
  }

  public static double getDEFAULT_METRES_PER_POINT() {
    return NoiseUtilsJNI.DEFAULT_METRES_PER_POINT_get();
  }

}
