/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class NoiseMapBuilderCylinder extends NoiseMapBuilder {
  private transient long swigCPtr;

  public NoiseMapBuilderCylinder(long cPtr, boolean cMemoryOwn) {
    super(NoiseUtilsJNI.NoiseMapBuilderCylinder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(NoiseMapBuilderCylinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_NoiseMapBuilderCylinder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NoiseMapBuilderCylinder() {
    this(NoiseUtilsJNI.new_NoiseMapBuilderCylinder(), true);
  }

  public void Build() {
    NoiseUtilsJNI.NoiseMapBuilderCylinder_Build(swigCPtr, this);
  }

  public double GetLowerAngleBound() {
    return NoiseUtilsJNI.NoiseMapBuilderCylinder_GetLowerAngleBound(swigCPtr, this);
  }

  public double GetLowerHeightBound() {
    return NoiseUtilsJNI.NoiseMapBuilderCylinder_GetLowerHeightBound(swigCPtr, this);
  }

  public double GetUpperAngleBound() {
    return NoiseUtilsJNI.NoiseMapBuilderCylinder_GetUpperAngleBound(swigCPtr, this);
  }

  public double GetUpperHeightBound() {
    return NoiseUtilsJNI.NoiseMapBuilderCylinder_GetUpperHeightBound(swigCPtr, this);
  }

  public void SetBounds(double lowerAngleBound, double upperAngleBound, double lowerHeightBound, double upperHeightBound) {
    NoiseUtilsJNI.NoiseMapBuilderCylinder_SetBounds(swigCPtr, this, lowerAngleBound, upperAngleBound, lowerHeightBound, upperHeightBound);
  }

}
