/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class NoiseMapBuilderSphere extends NoiseMapBuilder {
  private transient long swigCPtr;

  public NoiseMapBuilderSphere(long cPtr, boolean cMemoryOwn) {
    super(NoiseUtilsJNI.NoiseMapBuilderSphere_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(NoiseMapBuilderSphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_NoiseMapBuilderSphere(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NoiseMapBuilderSphere() {
    this(NoiseUtilsJNI.new_NoiseMapBuilderSphere(), true);
  }

  public void Build() {
    NoiseUtilsJNI.NoiseMapBuilderSphere_Build(swigCPtr, this);
  }

  public double GetEastLonBound() {
    return NoiseUtilsJNI.NoiseMapBuilderSphere_GetEastLonBound(swigCPtr, this);
  }

  public double GetNorthLatBound() {
    return NoiseUtilsJNI.NoiseMapBuilderSphere_GetNorthLatBound(swigCPtr, this);
  }

  public double GetSouthLatBound() {
    return NoiseUtilsJNI.NoiseMapBuilderSphere_GetSouthLatBound(swigCPtr, this);
  }

  public double GetWestLonBound() {
    return NoiseUtilsJNI.NoiseMapBuilderSphere_GetWestLonBound(swigCPtr, this);
  }

  public void SetBounds(double southLatBound, double northLatBound, double westLonBound, double eastLonBound) {
    NoiseUtilsJNI.NoiseMapBuilderSphere_SetBounds(swigCPtr, this, southLatBound, northLatBound, westLonBound, eastLonBound);
  }

}
