/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.utils;

import net.xbwee.libnoise.module.Module;

public class WriterBMP {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public WriterBMP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(WriterBMP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseUtilsJNI.delete_WriterBMP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WriterBMP() {
    this(NoiseUtilsJNI.new_WriterBMP(), true);
  }

  public String GetDestFilename() {
    return NoiseUtilsJNI.WriterBMP_GetDestFilename(swigCPtr, this);
  }

  public void SetDestFilename(String filename) {
    NoiseUtilsJNI.WriterBMP_SetDestFilename(swigCPtr, this, filename);
  }

  public void SetSourceImage(Image sourceImage) {
    NoiseUtilsJNI.WriterBMP_SetSourceImage(swigCPtr, this, Image.getCPtr(sourceImage), sourceImage);
  }

  public void WriteDestFile() {
    NoiseUtilsJNI.WriterBMP_WriteDestFile(swigCPtr, this);
  }

}
