/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class Blend extends Module {
  private transient long swigCPtr;

  public Blend(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Blend_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Blend obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Blend(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Blend() {
    this(NoiseModuleJNI.new_Blend(), true);
  }

  public Module GetControlModule() {
    return new Module(NoiseModuleJNI.Blend_GetControlModule(swigCPtr, this), false);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Blend_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Blend_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetControlModule(Module controlModule) {
    NoiseModuleJNI.Blend_SetControlModule(swigCPtr, this, Module.getCPtr(controlModule), controlModule);
  }

}
