/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class Cache extends Module {
  private transient long swigCPtr;

  public Cache(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Cache_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Cache obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Cache(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Cache() {
    this(NoiseModuleJNI.new_Cache(), true);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Cache_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Cache_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetSourceModule(int index, Module sourceModule) {
    NoiseModuleJNI.Cache_SetSourceModule(swigCPtr, this, index, Module.getCPtr(sourceModule), sourceModule);
  }

}
