/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class Clamp extends Module {
  private transient long swigCPtr;

  public Clamp(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Clamp_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Clamp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Clamp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Clamp() {
    this(NoiseModuleJNI.new_Clamp(), true);
  }

  public double GetLowerBound() {
    return NoiseModuleJNI.Clamp_GetLowerBound(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Clamp_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetUpperBound() {
    return NoiseModuleJNI.Clamp_GetUpperBound(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Clamp_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetBounds(double lowerBound, double upperBound) {
    NoiseModuleJNI.Clamp_SetBounds(swigCPtr, this, lowerBound, upperBound);
  }

}
