/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class Cylinders extends Module {
  private transient long swigCPtr;

  public Cylinders(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Cylinders_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Cylinders obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Cylinders(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Cylinders() {
    this(NoiseModuleJNI.new_Cylinders(), true);
  }

  public double GetFrequency() {
    return NoiseModuleJNI.Cylinders_GetFrequency(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Cylinders_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Cylinders_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetFrequency(double frequency) {
    NoiseModuleJNI.Cylinders_SetFrequency(swigCPtr, this, frequency);
  }

}
