/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class Module {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Module(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Module obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Module(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Module GetSourceModule(int index) {
    return new Module(NoiseModuleJNI.Module_GetSourceModule(swigCPtr, this, index), false);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Module_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Module_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetSourceModule(int index, Module sourceModule) {
    NoiseModuleJNI.Module_SetSourceModule(swigCPtr, this, index, Module.getCPtr(sourceModule), sourceModule);
  }

}
