/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

public class NoiseModule {
  public static double getDEFAULT_BILLOW_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_BILLOW_FREQUENCY_get();
  }

  public static double getDEFAULT_BILLOW_LACUNARITY() {
    return NoiseModuleJNI.DEFAULT_BILLOW_LACUNARITY_get();
  }

  public static int getDEFAULT_BILLOW_OCTAVE_COUNT() {
    return NoiseModuleJNI.DEFAULT_BILLOW_OCTAVE_COUNT_get();
  }

  public static double getDEFAULT_BILLOW_PERSISTENCE() {
    return NoiseModuleJNI.DEFAULT_BILLOW_PERSISTENCE_get();
  }

  public static NoiseQuality getDEFAULT_BILLOW_QUALITY() {
    return NoiseQuality.swigToEnum(NoiseModuleJNI.DEFAULT_BILLOW_QUALITY_get());
  }

  public static int getDEFAULT_BILLOW_SEED() {
    return NoiseModuleJNI.DEFAULT_BILLOW_SEED_get();
  }

  public static int getBILLOW_MAX_OCTAVE() {
    return NoiseModuleJNI.BILLOW_MAX_OCTAVE_get();
  }

  public static double getDEFAULT_CLAMP_LOWER_BOUND() {
    return NoiseModuleJNI.DEFAULT_CLAMP_LOWER_BOUND_get();
  }

  public static double getDEFAULT_CLAMP_UPPER_BOUND() {
    return NoiseModuleJNI.DEFAULT_CLAMP_UPPER_BOUND_get();
  }

  public static double getDEFAULT_CONST_VALUE() {
    return NoiseModuleJNI.DEFAULT_CONST_VALUE_get();
  }

  public static double getDEFAULT_CYLINDERS_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_CYLINDERS_FREQUENCY_get();
  }

  public static double getDEFAULT_EXPONENT() {
    return NoiseModuleJNI.DEFAULT_EXPONENT_get();
  }

  public static double getDEFAULT_PERLIN_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_PERLIN_FREQUENCY_get();
  }

  public static double getDEFAULT_PERLIN_LACUNARITY() {
    return NoiseModuleJNI.DEFAULT_PERLIN_LACUNARITY_get();
  }

  public static int getDEFAULT_PERLIN_OCTAVE_COUNT() {
    return NoiseModuleJNI.DEFAULT_PERLIN_OCTAVE_COUNT_get();
  }

  public static double getDEFAULT_PERLIN_PERSISTENCE() {
    return NoiseModuleJNI.DEFAULT_PERLIN_PERSISTENCE_get();
  }

  public static NoiseQuality getDEFAULT_PERLIN_QUALITY() {
    return NoiseQuality.swigToEnum(NoiseModuleJNI.DEFAULT_PERLIN_QUALITY_get());
  }

  public static int getDEFAULT_PERLIN_SEED() {
    return NoiseModuleJNI.DEFAULT_PERLIN_SEED_get();
  }

  public static int getPERLIN_MAX_OCTAVE() {
    return NoiseModuleJNI.PERLIN_MAX_OCTAVE_get();
  }

  public static double getDEFAULT_RIDGED_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_RIDGED_FREQUENCY_get();
  }

  public static double getDEFAULT_RIDGED_LACUNARITY() {
    return NoiseModuleJNI.DEFAULT_RIDGED_LACUNARITY_get();
  }

  public static int getDEFAULT_RIDGED_OCTAVE_COUNT() {
    return NoiseModuleJNI.DEFAULT_RIDGED_OCTAVE_COUNT_get();
  }

  public static NoiseQuality getDEFAULT_RIDGED_QUALITY() {
    return NoiseQuality.swigToEnum(NoiseModuleJNI.DEFAULT_RIDGED_QUALITY_get());
  }

  public static int getDEFAULT_RIDGED_SEED() {
    return NoiseModuleJNI.DEFAULT_RIDGED_SEED_get();
  }

  public static int getRIDGED_MAX_OCTAVE() {
    return NoiseModuleJNI.RIDGED_MAX_OCTAVE_get();
  }

  public static double getDEFAULT_ROTATE_X() {
    return NoiseModuleJNI.DEFAULT_ROTATE_X_get();
  }

  public static double getDEFAULT_ROTATE_Y() {
    return NoiseModuleJNI.DEFAULT_ROTATE_Y_get();
  }

  public static double getDEFAULT_ROTATE_Z() {
    return NoiseModuleJNI.DEFAULT_ROTATE_Z_get();
  }

  public static double getDEFAULT_BIAS() {
    return NoiseModuleJNI.DEFAULT_BIAS_get();
  }

  public static double getDEFAULT_SCALE() {
    return NoiseModuleJNI.DEFAULT_SCALE_get();
  }

  public static double getDEFAULT_SCALE_POINT_X() {
    return NoiseModuleJNI.DEFAULT_SCALE_POINT_X_get();
  }

  public static double getDEFAULT_SCALE_POINT_Y() {
    return NoiseModuleJNI.DEFAULT_SCALE_POINT_Y_get();
  }

  public static double getDEFAULT_SCALE_POINT_Z() {
    return NoiseModuleJNI.DEFAULT_SCALE_POINT_Z_get();
  }

  public static double getDEFAULT_SELECT_EDGE_FALLOFF() {
    return NoiseModuleJNI.DEFAULT_SELECT_EDGE_FALLOFF_get();
  }

  public static double getDEFAULT_SELECT_LOWER_BOUND() {
    return NoiseModuleJNI.DEFAULT_SELECT_LOWER_BOUND_get();
  }

  public static double getDEFAULT_SELECT_UPPER_BOUND() {
    return NoiseModuleJNI.DEFAULT_SELECT_UPPER_BOUND_get();
  }

  public static double getDEFAULT_SPHERES_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_SPHERES_FREQUENCY_get();
  }

  public static double getDEFAULT_TRANSLATE_POINT_X() {
    return NoiseModuleJNI.DEFAULT_TRANSLATE_POINT_X_get();
  }

  public static double getDEFAULT_TRANSLATE_POINT_Y() {
    return NoiseModuleJNI.DEFAULT_TRANSLATE_POINT_Y_get();
  }

  public static double getDEFAULT_TRANSLATE_POINT_Z() {
    return NoiseModuleJNI.DEFAULT_TRANSLATE_POINT_Z_get();
  }

  public static double getDEFAULT_TURBULENCE_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_TURBULENCE_FREQUENCY_get();
  }

  public static double getDEFAULT_TURBULENCE_POWER() {
    return NoiseModuleJNI.DEFAULT_TURBULENCE_POWER_get();
  }

  public static int getDEFAULT_TURBULENCE_ROUGHNESS() {
    return NoiseModuleJNI.DEFAULT_TURBULENCE_ROUGHNESS_get();
  }

  public static int getDEFAULT_TURBULENCE_SEED() {
    return NoiseModuleJNI.DEFAULT_TURBULENCE_SEED_get();
  }

  public static double getDEFAULT_VORONOI_DISPLACEMENT() {
    return NoiseModuleJNI.DEFAULT_VORONOI_DISPLACEMENT_get();
  }

  public static double getDEFAULT_VORONOI_FREQUENCY() {
    return NoiseModuleJNI.DEFAULT_VORONOI_FREQUENCY_get();
  }

  public static int getDEFAULT_VORONOI_SEED() {
    return NoiseModuleJNI.DEFAULT_VORONOI_SEED_get();
  }

}
