/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.module;

import net.xbwee.libnoise.noise.NoiseQuality;

public class ScaleBias extends Module {
  private transient long swigCPtr;

  public ScaleBias(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.ScaleBias_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ScaleBias obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_ScaleBias(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ScaleBias() {
    this(NoiseModuleJNI.new_ScaleBias(), true);
  }

  public double GetBias() {
    return NoiseModuleJNI.ScaleBias_GetBias(swigCPtr, this);
  }

  public double GetScale() {
    return NoiseModuleJNI.ScaleBias_GetScale(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.ScaleBias_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.ScaleBias_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetBias(double bias) {
    NoiseModuleJNI.ScaleBias_SetBias(swigCPtr, this, bias);
  }

  public void SetScale(double scale) {
    NoiseModuleJNI.ScaleBias_SetScale(swigCPtr, this, scale);
  }

}
