/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class Const extends Module {
  private transient long swigCPtr;

  protected Const(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Const_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Const obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Const(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Const() {
    this(NoiseModuleJNI.new_Const(), true);
  }

  public double GetConstValue() {
    return NoiseModuleJNI.Const_GetConstValue(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Const_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Const_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetConstValue(double constValue) {
    NoiseModuleJNI.Const_SetConstValue(swigCPtr, this, constValue);
  }

}
