/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class ControlPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ControlPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ControlPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_ControlPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInputValue(double value) {
    NoiseModuleJNI.ControlPoint_inputValue_set(swigCPtr, this, value);
  }

  public double getInputValue() {
    return NoiseModuleJNI.ControlPoint_inputValue_get(swigCPtr, this);
  }

  public void setOutputValue(double value) {
    NoiseModuleJNI.ControlPoint_outputValue_set(swigCPtr, this, value);
  }

  public double getOutputValue() {
    return NoiseModuleJNI.ControlPoint_outputValue_get(swigCPtr, this);
  }

  public ControlPoint() {
    this(NoiseModuleJNI.new_ControlPoint(), true);
  }

}
