/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class Perlin extends Module {
  private transient long swigCPtr;

  protected Perlin(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Perlin_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Perlin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Perlin(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Perlin() {
    this(NoiseModuleJNI.new_Perlin(), true);
  }

  public double GetFrequency() {
    return NoiseModuleJNI.Perlin_GetFrequency(swigCPtr, this);
  }

  public double GetLacunarity() {
    return NoiseModuleJNI.Perlin_GetLacunarity(swigCPtr, this);
  }

  public SWIGTYPE_p_noise__NoiseQuality GetNoiseQuality() {
    return new SWIGTYPE_p_noise__NoiseQuality(NoiseModuleJNI.Perlin_GetNoiseQuality(swigCPtr, this), true);
  }

  public int GetOctaveCount() {
    return NoiseModuleJNI.Perlin_GetOctaveCount(swigCPtr, this);
  }

  public double GetPersistence() {
    return NoiseModuleJNI.Perlin_GetPersistence(swigCPtr, this);
  }

  public int GetSeed() {
    return NoiseModuleJNI.Perlin_GetSeed(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Perlin_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Perlin_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetFrequency(double frequency) {
    NoiseModuleJNI.Perlin_SetFrequency(swigCPtr, this, frequency);
  }

  public void SetLacunarity(double lacunarity) {
    NoiseModuleJNI.Perlin_SetLacunarity(swigCPtr, this, lacunarity);
  }

  public void SetNoiseQuality(SWIGTYPE_p_noise__NoiseQuality noiseQuality) {
    NoiseModuleJNI.Perlin_SetNoiseQuality(swigCPtr, this, SWIGTYPE_p_noise__NoiseQuality.getCPtr(noiseQuality));
  }

  public void SetOctaveCount(int octaveCount) {
    NoiseModuleJNI.Perlin_SetOctaveCount(swigCPtr, this, octaveCount);
  }

  public void SetPersistence(double persistence) {
    NoiseModuleJNI.Perlin_SetPersistence(swigCPtr, this, persistence);
  }

  public void SetSeed(int seed) {
    NoiseModuleJNI.Perlin_SetSeed(swigCPtr, this, seed);
  }

}
