/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class RotatePoint extends Module {
  private transient long swigCPtr;

  protected RotatePoint(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.RotatePoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RotatePoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_RotatePoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RotatePoint() {
    this(NoiseModuleJNI.new_RotatePoint(), true);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.RotatePoint_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.RotatePoint_GetValue(swigCPtr, this, x, y, z);
  }

  public double GetXAngle() {
    return NoiseModuleJNI.RotatePoint_GetXAngle(swigCPtr, this);
  }

  public double GetYAngle() {
    return NoiseModuleJNI.RotatePoint_GetYAngle(swigCPtr, this);
  }

  public double GetZAngle() {
    return NoiseModuleJNI.RotatePoint_GetZAngle(swigCPtr, this);
  }

  public void SetAngles(double xAngle, double yAngle, double zAngle) {
    NoiseModuleJNI.RotatePoint_SetAngles(swigCPtr, this, xAngle, yAngle, zAngle);
  }

  public void SetXAngle(double xAngle) {
    NoiseModuleJNI.RotatePoint_SetXAngle(swigCPtr, this, xAngle);
  }

  public void SetYAngle(double yAngle) {
    NoiseModuleJNI.RotatePoint_SetYAngle(swigCPtr, this, yAngle);
  }

  public void SetZAngle(double zAngle) {
    NoiseModuleJNI.RotatePoint_SetZAngle(swigCPtr, this, zAngle);
  }

}
