/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class Terrace extends Module {
  private transient long swigCPtr;

  protected Terrace(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Terrace_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Terrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Terrace(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Terrace() {
    this(NoiseModuleJNI.new_Terrace(), true);
  }

  public void AddControlPoint(double value) {
    NoiseModuleJNI.Terrace_AddControlPoint(swigCPtr, this, value);
  }

  public void ClearAllControlPoints() {
    NoiseModuleJNI.Terrace_ClearAllControlPoints(swigCPtr, this);
  }

  public SWIGTYPE_p_double GetControlPointArray() {
    long cPtr = NoiseModuleJNI.Terrace_GetControlPointArray(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public int GetControlPointCount() {
    return NoiseModuleJNI.Terrace_GetControlPointCount(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Terrace_GetSourceModuleCount(swigCPtr, this);
  }

  public void InvertTerraces(boolean invert) {
    NoiseModuleJNI.Terrace_InvertTerraces__SWIG_0(swigCPtr, this, invert);
  }

  public void InvertTerraces() {
    NoiseModuleJNI.Terrace_InvertTerraces__SWIG_1(swigCPtr, this);
  }

  public boolean IsTerracesInverted() {
    return NoiseModuleJNI.Terrace_IsTerracesInverted(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Terrace_GetValue(swigCPtr, this, x, y, z);
  }

  public void MakeControlPoints(int controlPointCount) {
    NoiseModuleJNI.Terrace_MakeControlPoints(swigCPtr, this, controlPointCount);
  }

}
