/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.module;

public class Turbulence extends Module {
  private transient long swigCPtr;

  protected Turbulence(long cPtr, boolean cMemoryOwn) {
    super(NoiseModuleJNI.Turbulence_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Turbulence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModuleJNI.delete_Turbulence(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Turbulence() {
    this(NoiseModuleJNI.new_Turbulence(), true);
  }

  public double GetFrequency() {
    return NoiseModuleJNI.Turbulence_GetFrequency(swigCPtr, this);
  }

  public double GetPower() {
    return NoiseModuleJNI.Turbulence_GetPower(swigCPtr, this);
  }

  public int GetRoughnessCount() {
    return NoiseModuleJNI.Turbulence_GetRoughnessCount(swigCPtr, this);
  }

  public int GetSeed() {
    return NoiseModuleJNI.Turbulence_GetSeed(swigCPtr, this);
  }

  public int GetSourceModuleCount() {
    return NoiseModuleJNI.Turbulence_GetSourceModuleCount(swigCPtr, this);
  }

  public double GetValue(double x, double y, double z) {
    return NoiseModuleJNI.Turbulence_GetValue(swigCPtr, this, x, y, z);
  }

  public void SetFrequency(double frequency) {
    NoiseModuleJNI.Turbulence_SetFrequency(swigCPtr, this, frequency);
  }

  public void SetPower(double power) {
    NoiseModuleJNI.Turbulence_SetPower(swigCPtr, this, power);
  }

  public void SetRoughness(int roughness) {
    NoiseModuleJNI.Turbulence_SetRoughness(swigCPtr, this, roughness);
  }

  public void SetSeed(int seed) {
    NoiseModuleJNI.Turbulence_SetSeed(swigCPtr, this, seed);
  }

}
