/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.noise;

public class NoiseJNI {
  public final static native void LatLonToXYZ(double jarg1, double jarg2, double[] jarg3, double[] jarg4, double[] jarg5);
  public final static native double GradientCoherentNoise3D__SWIG_0(double jarg1, double jarg2, double jarg3, int jarg4, int jarg5);
  public final static native double GradientCoherentNoise3D__SWIG_1(double jarg1, double jarg2, double jarg3, int jarg4);
  public final static native double GradientCoherentNoise3D__SWIG_2(double jarg1, double jarg2, double jarg3);
  public final static native double GradientNoise3D__SWIG_0(double jarg1, double jarg2, double jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native double GradientNoise3D__SWIG_1(double jarg1, double jarg2, double jarg3, int jarg4, int jarg5, int jarg6);
  public final static native int IntValueNoise3D__SWIG_0(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int IntValueNoise3D__SWIG_1(int jarg1, int jarg2, int jarg3);
  public final static native double MakeInt32Range(double jarg1);
  public final static native double ValueCoherentNoise3D__SWIG_0(double jarg1, double jarg2, double jarg3, int jarg4, int jarg5);
  public final static native double ValueCoherentNoise3D__SWIG_1(double jarg1, double jarg2, double jarg3, int jarg4);
  public final static native double ValueCoherentNoise3D__SWIG_2(double jarg1, double jarg2, double jarg3);
  public final static native double ValueNoise3D__SWIG_0(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native double ValueNoise3D__SWIG_1(int jarg1, int jarg2, int jarg3);
}
