/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.libnoise.model;

import net.xbwee.libnoise.module.Module;

public class Cylinder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Cylinder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Cylinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NoiseModelJNI.delete_Cylinder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Cylinder() {
    this(NoiseModelJNI.new_Cylinder__SWIG_0(), true);
  }

  public Cylinder(Module module) {
    this(NoiseModelJNI.new_Cylinder__SWIG_1(Module.getCPtr(module), module), true);
  }

  public Module GetModule() {
    return new Module(NoiseModelJNI.Cylinder_GetModule(swigCPtr, this), false);
  }

  public double GetValue(double angle, double height) {
    return NoiseModelJNI.Cylinder_GetValue(swigCPtr, this, angle, height);
  }

  public void SetModule(Module module) {
    NoiseModelJNI.Cylinder_SetModule(swigCPtr, this, Module.getCPtr(module), module);
  }

}
