/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.xbwee.noise.model;

public class NoiseModelJNI {
  public final static native long new_Cylinder__SWIG_0();
  public final static native long new_Cylinder__SWIG_1(long jarg1);
  public final static native long Cylinder_GetModule(long jarg1, Cylinder jarg1_);
  public final static native double Cylinder_GetValue(long jarg1, Cylinder jarg1_, double jarg2, double jarg3);
  public final static native void Cylinder_SetModule(long jarg1, Cylinder jarg1_, long jarg2);
  public final static native void delete_Cylinder(long jarg1);
  public final static native long new_Line__SWIG_0();
  public final static native long new_Line__SWIG_1(long jarg1);
  public final static native boolean Line_GetAttenuate(long jarg1, Line jarg1_);
  public final static native long Line_GetModule(long jarg1, Line jarg1_);
  public final static native double Line_GetValue(long jarg1, Line jarg1_, double jarg2);
  public final static native void Line_SetAttenuate(long jarg1, Line jarg1_, boolean jarg2);
  public final static native void Line_SetEndPoint(long jarg1, Line jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native void Line_SetModule(long jarg1, Line jarg1_, long jarg2);
  public final static native void Line_SetStartPoint(long jarg1, Line jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native void delete_Line(long jarg1);
  public final static native long new_Plane__SWIG_0();
  public final static native long new_Plane__SWIG_1(long jarg1);
  public final static native long Plane_GetModule(long jarg1, Plane jarg1_);
  public final static native double Plane_GetValue(long jarg1, Plane jarg1_, double jarg2, double jarg3);
  public final static native void Plane_SetModule(long jarg1, Plane jarg1_, long jarg2);
  public final static native void delete_Plane(long jarg1);
  public final static native long new_Sphere__SWIG_0();
  public final static native long new_Sphere__SWIG_1(long jarg1);
  public final static native long Sphere_GetModule(long jarg1, Sphere jarg1_);
  public final static native double Sphere_GetValue(long jarg1, Sphere jarg1_, double jarg2, double jarg3);
  public final static native void Sphere_SetModule(long jarg1, Sphere jarg1_, long jarg2);
  public final static native void delete_Sphere(long jarg1);
}
